name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: docker build . --file Dockerfile --tag $REGISTRY_USER/demo:latest
    - name: Tag the Docker image
      run: | 
          GIT_SHA="$(git rev-parse --short HEAD)"
          docker tag $REGISTRY_USER/demo:latest $REGISTRY_USER/demo:$GIT_SHA
    - name: Login to Docker Hub
      run: docker login --username $REGISTRY_USER --password $REGISTRY_PASSWORD
    - name: Push the Docker image
      run: |
        docker push $REGISTRY_USER/demo:latest
        docker push $REGISTRY_USER/demo:$GIT_SHA
